create table if not exists "user" (
  id bigint generated by default as identity primary key,
  username varchar(64) not null,
  password_hash varchar(255) not null,
  real_name varchar(64) not null,
  role varchar(16) not null,
  phone varchar(32),
  email varchar(128),
  status varchar(16) not null default 'ACTIVE',
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_user_username unique (username),
  constraint ck_user_role check (role in ('STUDENT', 'TEACHER', 'ADMIN')),
  constraint ck_user_status check (status in ('ACTIVE', 'DISABLED'))
);

create table if not exists student (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  student_no varchar(32) not null,
  class_name varchar(64),
  grade varchar(16),
  major varchar(64),
  political_status varchar(32),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_student_user unique (user_id),
  constraint uq_student_student_no unique (student_no),
  constraint fk_student_user foreign key (user_id) references "user"(id)
);

create table if not exists teacher (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  teacher_no varchar(32) not null,
  department varchar(64),
  title varchar(64),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_teacher_user unique (user_id),
  constraint uq_teacher_teacher_no unique (teacher_no),
  constraint fk_teacher_user foreign key (user_id) references "user"(id)
);

create index if not exists idx_user_role on "user"(role);
create index if not exists idx_user_status on "user"(status);
create index if not exists idx_student_class_grade on student(class_name, grade);
create index if not exists idx_teacher_department on teacher(department);

create table if not exists notification (
  id             bigint generated by default as identity primary key,
  receiver_id    bigint       not null,                  
  title          varchar(128) not null,                  
  content        text         not null,                  
  notification_type varchar(16) not null default 'NOTICE', 
  biz_type       varchar(32),                            
  biz_id         bigint,                                 
  read_status    varchar(8)   not null default 'UNREAD', 
  created_at     timestamp    not null default now(),
  read_at        timestamp,                              

  constraint fk_notification_receiver
    foreign key (receiver_id) references "user"(id),
  constraint ck_notification_type
    check (notification_type in ('NOTICE', 'TODO')),
  constraint ck_notification_read_status
    check (read_status in ('UNREAD', 'READ'))
);

create index if not exists idx_notification_receiver_read
  on notification(receiver_id, read_status);

create index if not exists idx_notification_biz
  on notification(biz_type, biz_id);

create index if not exists idx_notification_created
  on notification(created_at desc);



create table if not exists operation_log (
  id               bigint generated by default as identity primary key,
  user_id          bigint,                               
  operation_type   varchar(32)  not null,                
  operation_content text,                               
  biz_type         varchar(32),                         
  biz_id           bigint,                               
  result           varchar(8)   not null default 'SUCCESS', 
  fail_reason      varchar(255),                         
  ip_address       varchar(45),                          
  user_agent       varchar(512),                         
  request_id       varchar(64),                          
  operation_time   timestamp    not null default now(),

  constraint fk_operation_log_user
    foreign key (user_id) references "user"(id),
  constraint ck_operation_log_result
    check (result in ('SUCCESS', 'FAIL'))
);


create index if not exists idx_operation_log_user
  on operation_log(user_id);


create index if not exists idx_operation_log_type
  on operation_log(operation_type);


create index if not exists idx_operation_log_time
  on operation_log(operation_time desc);


create index if not exists idx_operation_log_biz
  on operation_log(biz_type, biz_id);