create table if not exists "user" (
  id bigint generated by default as identity primary key,
  username varchar(64) not null,
  password_hash varchar(255) not null,
  real_name varchar(64) not null,
  role varchar(16) not null,
  phone varchar(32),
  email varchar(128),
  status varchar(16) not null default 'ACTIVE',
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_user_username unique (username),
  constraint ck_user_role check (role in ('STUDENT', 'TEACHER', 'ADMIN')),
  constraint ck_user_status check (status in ('ACTIVE', 'DISABLED'))
);

create table if not exists student (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  student_no varchar(32) not null,
  class_name varchar(64),
  grade varchar(16),
  major varchar(64),
  political_status varchar(32),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_student_user unique (user_id),
  constraint uq_student_student_no unique (student_no),
  constraint fk_student_user foreign key (user_id) references "user"(id)
);

create table if not exists teacher (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  teacher_no varchar(32) not null,
  department varchar(64),
  title varchar(64),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  constraint uq_teacher_user unique (user_id),
  constraint uq_teacher_teacher_no unique (teacher_no),
  constraint fk_teacher_user foreign key (user_id) references "user"(id)
);

create index if not exists idx_user_role on "user"(role);
create index if not exists idx_user_status on "user"(status);
create index if not exists idx_student_class_grade on student(class_name, grade);
create index if not exists idx_teacher_department on teacher(department);
