-- 成员 D：文件存储服务与统计报表模块
-- 说明：file_record 为 D 模块自有表；material/student_process/certificate_application
-- 的兼容建表只在 A/B 表尚未导入时生效，避免本模块统计接口因缺表无法演示。

BEGIN;

CREATE TABLE IF NOT EXISTS file_record (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id       BIGINT       NOT NULL,
  related_type   VARCHAR(32)  NOT NULL DEFAULT 'OTHER',
  related_id     BIGINT,
  original_name  VARCHAR(255) NOT NULL,
  stored_name    VARCHAR(512) NOT NULL,
  file_url       VARCHAR(512) NOT NULL,
  content_type   VARCHAR(128),
  file_size      BIGINT       NOT NULL DEFAULT 0,
  status         VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_file_record_owner FOREIGN KEY (owner_id) REFERENCES "user"(id),
  CONSTRAINT ck_file_record_status CHECK (status IN ('ACTIVE', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_file_record_owner ON file_record(owner_id);
CREATE INDEX IF NOT EXISTS idx_file_record_related ON file_record(related_type, related_id);
CREATE INDEX IF NOT EXISTS idx_file_record_created ON file_record(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_file_record_status ON file_record(status);

-- 兼容 A 组 material 表字段，用于文件元数据和统计报表联调。
CREATE TABLE IF NOT EXISTS material (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     BIGINT,
  node_id        BIGINT,
  material_type  VARCHAR(64),
  file_url       VARCHAR(512),
  file_name      VARCHAR(255),
  description    VARCHAR(1024),
  status         VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  submit_time    TIMESTAMP,
  created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_material_status CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'RETURNED'))
);

CREATE INDEX IF NOT EXISTS idx_material_student ON material(student_id);
CREATE INDEX IF NOT EXISTS idx_material_node ON material(node_id);
CREATE INDEX IF NOT EXISTS idx_material_status ON material(status);
CREATE INDEX IF NOT EXISTS idx_material_submit_time ON material(submit_time DESC);

CREATE TABLE IF NOT EXISTS student_process (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id       BIGINT,
  process_id       BIGINT,
  current_node_id  BIGINT,
  status           VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS',
  start_time       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_student_process_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELED'))
);

CREATE INDEX IF NOT EXISTS idx_student_process_student ON student_process(student_id);
CREATE INDEX IF NOT EXISTS idx_student_process_status ON student_process(status);
CREATE INDEX IF NOT EXISTS idx_student_process_current_node ON student_process(current_node_id);

-- 兼容 B 组证明申请统计。如果 B 表已存在，本语句不会改动其正式结构。
CREATE TABLE IF NOT EXISTS certificate_application (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id       BIGINT,
  cert_type        VARCHAR(64) NOT NULL,
  title            VARCHAR(256),
  description      VARCHAR(1024),
  attachment_url   VARCHAR(512),
  attachment_name  VARCHAR(256),
  status           VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  approver_id      BIGINT,
  approve_comment  VARCHAR(1024),
  pdf_url          VARCHAR(512),
  apply_time       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approve_time     TIMESTAMP,
  issue_time       TIMESTAMP,
  update_time      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cert_student_id ON certificate_application(student_id);
CREATE INDEX IF NOT EXISTS idx_cert_cert_type ON certificate_application(cert_type);
CREATE INDEX IF NOT EXISTS idx_cert_status ON certificate_application(status);
CREATE INDEX IF NOT EXISTS idx_cert_apply_time ON certificate_application(apply_time DESC);

COMMIT;
